### ISSUE TITLE
Logging custom objects should JSON serialize instead of using ToString

### ISSUE THREAD

**Issue by siimonchoi** [open-telemetry/opentelemetry-dotnet-contrib#1527]
# Issue with OpenTelemetry.Exporter.Geneva

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 1.3.2`):

[OpenTelemetry.Exporter.Geneva 1.7.0](https://www.nuget.org/packages/OpenTelemetry.Exporter.Geneva/1.7.0)

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

`net6.0`

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**

I'd like to see if there is a way for GenevaExporter to JSON serialize custom objects.

What do you expect to see?

custom objects should be logged as a JSON serialized string.

**What is the actual behavior?**

In the Serialize method in MessagePackSerializer, a custom object will fall into the [switch's default case](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MessagePackSerializer.cs#L657) which calls `ToString()`. This will return the type name which is not greatly useful. 

## Additional Context

Add any other context about the feature request here.

**Comment by CodeBlanch** [comment]
@siimonchoi 

I don't think this is a change we are prepared to make yet. We are still in discussions with the agent team about how best to represent complex types.

The `MessagePackSerializer` does have support for complex types if they implement `IDictionary<string, object>`. What will happen in that case is each item in the dictionary is written out in message pack format. If we switch the default case to JSON and left that behavior alone, it would probably be very confusing. But don't rush to implement `IDictionary<string, object>` just yet, because there are issues with how the agent parses that data as well.

A couple options to workaround the issue...

* Switch to the TLD format by adding `PrivatePreviewEnableTraceLoggingDynamic=true` to your connection string. If you do that, JSON is used instead of message pack. The TLD code has the [same default clause](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/8a89a69445a1f89917a6a159e895b9267c7cc925/src/OpenTelemetry.Exporter.Geneva/TLDExporter/JsonSerializer.cs#L338) but it also [supports IEnumerable<KeyValuePair<string, object>>](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/8a89a69445a1f89917a6a159e895b9267c7cc925/src/OpenTelemetry.Exporter.Geneva/TLDExporter/JsonSerializer.cs#L318) which may be easier to implement on your objects. You potentially can utilize the [Logging with Complex Objects](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/complex-objects) style to have that interface implementation rolled for you automatically by a source generator.

* If you want to brute force JSON, you could do something like this...

   ```csharp
    private readonly struct LogToJsonWrapper
    {
        private readonly object instance;

        public LogToJsonWrapper(object instance)
        {
            this.instance = instance;
        }

        public override string ToString()
        {
            return JsonSerializer.Serialize(this.instance);
        }
    }

   logger.LogInformation("{request}", new LogToJsonWrapper(customObject));
   ```

**Comment by CodeBlanch** [comment]
I'm going to close this for now. Anyone reading this please comment if this feature is important to you so we can track the demand.
