### ISSUE TITLE
Provide a Serilog renderer

### ISSUE THREAD

**Issue by thompson-tomo** [open-telemetry/opentelemetry-dotnet-contrib#1702]
**What are you trying to achieve?**

I want my structured logging to mirror the structure of the OTLP model. This is so that i can use an agent to upload my files to an OTLP endpoint. This will mean that we would need, a couple of layouts -> Traces, Metrics etc and able to specify that layout like we do with Elastic.CommonSchema for Serilog.

**Additional context.**

Logging exporter has been raised as #1700 & #1701 is the nlog target issue

**Comment by martinjt** [comment]
This would be something that those projects would need to support. The OpenTelemetry project would not be providing this kind of output.

For file uploading, look at the OpenTelemetry collector, run it on the machine, and have that write these to files so that it can be used in a separate location to upload them.
