### ISSUE TITLE
[bug] OpenTelemetry.Exporter.Geneva does not fail at startup when socket unreachable

### ISSUE THREAD

**Issue by cataggar** [open-telemetry/opentelemetry-dotnet-contrib#2258]
### Component

OpenTelemetry.Exporter.Geneva

### Package Version

- OpenTelemetry.Exporter.Geneva 1.6.0
- OpenTelemetry 1.6.0

We'll be upgrading to latest soon. Probably next month.

### Runtime Version

net8.0

### Description

We had a production incident where the mdm socket was misconfigured. Before https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/935, the app would fail at startup. We may actually want that behavior back. I'm not sure. As a repair item, we need to ensure that do not have another similar incident.

### Steps to Reproduce

.

### Expected Result

An exception is thrown and startup fails.

### Actual Result

The error is swallowed.

**Comment by CodeBlanch** [comment]
This is by design. You may want it to fail, but other users don't ☹️ We decided this was the better direction because a more common thing is app and agent are both configured correctly but the agent hasn't completed its startup when the app is launched. With the current design everything will recover once the agent starts.

The long-term direction is to move to `user_events` where a socket isn't required.
