### ISSUE TITLE
FluentBit exporter

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet-contrib#31]
Define a data format and create an exporter from OpenTelemetry to FluentBit. This will allow customers to use existing log delivery pipeline to upload telemetry collected by the rich set of various OpenTelemetry SDKs.

This issue is features as a [Community Bridge](https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q3-q4/project_ideas.md#opentelemetry-to-fluentbit-exporter) project for Q3-Q4 2020.

**Comment by Syn3rman** [comment]
Hey @SergeyKanzhelev,

I'm interested in working on this project as part of community bridge. I'm currently going through the documentation for Opentelemetry and am setting up the collector locally to familiarise myself with the project, and even though the slots/projects selected are going to be announced on the 21st, is there anything else I can do in the meantime?
Also, I have previously worked with go but not dotnet, so would it be possible for the project scope to build a Fluentbit exporter for the otel collector since a [receiver](https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver/fluentforwardreceiver) has already been implemented?

Thanks!

**Comment by SergeyKanzhelev** [comment]
@Syn3rman thank you for your interest and welcome! Community Bridge defines a process of applying and interviewing candidates and only a few spots would be allocated for OpenTelemetry. Please make sure to register at community bridge web site and check for updates.

If this project will be picked, we can scope this project to Go, it shouldn't be a problem.

**Comment by Syn3rman** [comment]
Hey @SergeyKanzhelev,

Since the projects are now accepting applications and this project is participating under community bridge, could you tell me what the next steps in the application process will be? I've created a mentee profile on the community bridge website and started working on a [proposal](https://docs.google.com/document/d/1Gf2B2qHqk-DjuNFNEbYNaSFCM2Asq49Sj_eQESk8QeU/edit?usp=sharing) based on my understanding of the project, since I'm pretty sure that potential mentees need to upload a project proposal.

**Comment by SergeyKanzhelev** [comment]
yes, please upload short resume and project proposal on the community bridge website. Timeline is here: https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q3-q4/README.md#timeline

**Comment by Syn3rman** [comment]
I've submitted the application on the website!

**Comment by theadityasam** [comment]
Hey @SergeyKanzhelev 
I'm a final year undergraduate student developer from IIIT Bhubaneswar. I have demonstrated experience in C# as well as open source development. I would've liked to discuss the project awhile back, but unfortunately came across it recently. Nevertheless I've applied in community bridge with my resume and proposal. Hoping to hear from you soon!

**Comment by SergeyKanzhelev** [comment]
decided to go with GoLang. Will create a separate issue
