### ISSUE TITLE
Upload 0.7.0-beta1 release to NuGet

### ISSUE THREAD

**Issue by dbarbashov** [open-telemetry/opentelemetry-dotnet-contrib#46]
There is only 0.6.0-beta1 release available

**Comment by sergeyshaykhullin** [comment]
@eddynaka Please, update and upload to NuGet contrib packages to latest version, for now we can't use them with 1.0.0 rc.
Lately we had warnings but all is working =(

```
  Startup.cs(126, 6): [CS7069] Reference to type 'TracerProviderBuilder' claims it is defined in 'OpenTelemetry', but it could not be found
```

**Comment by eddynaka** [comment]
@sergeyshaykhullin , we are still checking how we will do that, since a lot of stuff changed and became internal.

I will try to update ASAP.

**Comment by eddynaka** [comment]
@sergeyshaykhullin , I tried the migration but that isn't easy since the prs that changed many classes to internal. We will have to wait some news from the main repo to migrate...

For now, this is a duplicate from https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/49, so I will close this for now. And, we will have to wait for this: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1580
