### ISSUE TITLE
What is the difference to `OpenTelemetry.Instrumentation.Runtime`

### ISSUE THREAD

**Issue by msschl** [open-telemetry/opentelemetry-dotnet-contrib#536]
What is the difference to the `OpenTelemetry.Instrumentation.Runtime` package and which one should you use to collect runtime metrics.

It seems like those two packages expose some identical metrics.

**Comment by cijothomas** [comment]
EventCounter instruemntation is general purpose - it can subscribe to any configured EventCounters, and turn them into OTel metrics.

Runtime instrumentation - is a instrumentation for a set of runtime metrics. The list is documented in the readme file.
(A lot of these metrics are also published via EventCounter as well.)

Once ready, EventCounter instrumentation will allow you to get a lot more metrics than runtime. This is simply because a lot more components write metrics using EventCounter.
