### ISSUE TITLE
Can we update MicrosoftExtensionsOptionsPkgVer?

### ISSUE THREAD

**Issue by ArminShoeibi** [open-telemetry/opentelemetry-dotnet-contrib#551]
Hi there, we are using many packages from this repository but we need to explicitly reference Microsoft.Extensions.Options in our projects, because of  version conflicts between different packages Like Microsoft.Extensions.Hosting 6.0.1 with https://www.nuget.org/packages/OpenTelemetry.Instrumentation.StackExchangeRedis/1.0.0-rc9.7

Can I update this value to 6 and send a PR?
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/e09211469ec38ced7cfa97e331b0751a2b2beaa9/build/Common.props#L29

**Comment by Kielek** [comment]
I do not think that it is good idea. If you change the version you will reduce the number of supported libraries.
It is especially important to keep this version as low as possible because it is used in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation. In AutoInstrumentation there is no possibility to rebuild project to force upgrades.

Could you please create some small reproduction project with you issue. I hope there is a possibility to workaround your issue.

**Comment by ArminShoeibi** [comment]
> I do not think that it is good idea. If you change the version you will reduce the number of supported libraries. It is especially important to keep this version as low as possible because it is used in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation. In AutoInstrumentation there is no possibility to rebuild project to force upgrades.
> 
> Could you please create some small reproduction project with you issue. I hope there is a possibility to workaround your issue.

Thanks,
Yes we have a workaround for it, we need to explicitly reference this package:
https://www.nuget.org/packages/Microsoft.Extensions.Options/6.0.0
