### ISSUE TITLE
EventName is not emitted to backend (Kusto, etc.)

### ISSUE THREAD

**Issue by craigktreasure** [open-telemetry/opentelemetry-dotnet-contrib#584]
# Issue with OpenTelemetry.Exporter.Geneva

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* [OpenTelemetry.Exporter.Geneva
  1.2.6](https://www.nuget.org/packages/OpenTelemetry.Exporter.Geneva/1.2.6)

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* `net6.0`

**Is this a feature request or a bug?**

* [x] Feature Request
* [x] Bug

(Hard to say)

**What is the expected behavior?**

I expect to see the [event name](https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.eventid.name?view=dotnet-plat-ext-6.0#microsoft-extensions-logging-eventid-name) emitted to Geneva.

**What is the actual behavior?**

The event name is not emitted to Geneva.

## Additional Context

I have discussed this a few times with @cijothomas. He sent a [PR](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/309) to address it, but it never got checked in.

**Comment by andhesky** [comment]
This is also important to my team. I also created [my own PR](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/804) before being directed to this issue and the existing PR.

I put justification in that PR, the short version is it greatly improves developer productivity when using [codegen'd log message](https://learn.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator) because developers frequently don't need to write a separate message as long as they get the EventName

**Comment by utpilla** [comment]
We plan to add support for this in the upcoming 1.5.0-alpha release which should be done in another two weeks.
