### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by imalkevich** [open-telemetry/opentelemetry-dotnet-contrib#681]
# Issue with OpenTelemetry.Exporter.Geneva - Cannot assign requested address

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* [OpenTelemetry.Exporter.Geneva 1.4.0-beta.1](https://www.nuget.org/packages/OpenTelemetry.Exporter.Geneva/1.4.0-beta.1)

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can find this information from the `*.csproj` file):

.NET 7.0 RC1

**Is this a feature request or a bug?**

* [ ] Feature Request
* [*] Bug

**What is the expected behavior?**

**No issues with logging**

What do you expect to see?

**Container is crashing with SIGSEGV code and in stack traces Cannot assign requested address errors**

## Additional Context

OpenTelemetry.Exporter.Geneva is used internally by R9 logging library (Microsoft.R9.Extensions.Logging.Exporters.Geneva.dll v1.22), and there are decent amount of crashes with the following stack trace:
![image](https://user-images.githubusercontent.com/7044304/194838025-87d9b4a6-6a14-4896-a5c6-ba2c94db608b.png)

Unfortunately I can't reproduce the issue and don't know the circumstances that trigger this issue, but every day there are 10-20 crashes of the same issue.

Thanks

**Comment by cijothomas** [comment]
1. The exception is thrown at startup (ie during initialization of OpenTelemetry GenevaExporter), and not during an actual Log statement.
	
2. The exception indicates the UDS endpoint is not available. (This also confirms that this is a Linux environment.)
	
3. If the UDS endpoint is not available at startup, it is by design to throw and let app crash (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/Exporter.Geneva-1.4.0.beta.1/src/OpenTelemetry.Exporter.Geneva/UnixDomainSocketDataTransport.cs#L88-L95)
	
4. If the UDS Endpoint was available at startup, but later become unavailable, Exporter will swallow the exception.
	
3,4 follows the general exception handling policies followed by OpenTelemetry SDKs (which allows to fail-fast by throwing exception, but does not allow throwing later after a successful initialization) - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/error-handling.md
