### ISSUE TITLE
Unexpected behaviour of OTel logs: custom columns, truncation

### ISSUE THREAD

**Issue by alamoot** [open-telemetry/opentelemetry-dotnet-contrib#802]
# Issue with OpenTelemetry.Exporter.Geneva

List of all OpenTelemetry NuGet:
```
<PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
<PackageReference Include="Microsoft.WindowsAzure.ConfigurationManager" Version="3.2.3" />
<PackageReference Include="OpenTelemetry.Exporter.Geneva" Version="1.1.1" />
```

Runtime version: .NetFramework 4.7.2 running on Azure 

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

Consider our logging example:
```C#
string message = sb.ToString() + " -- {jsonpayload} {tagid}, {deploymentid}";
string[] args = new string[] { jsonPayload, tagId, deploymentId };
OpenTelemetryLogger.logger.LogWarning(message, args);
```
the string builder has all the text to display in the default column, and at the end there are 3 extra columns. The values for those extra columns are provided on the second line, and only used to show up on the specific columns.

1. I should see custom column logs, only in custom columns. A custom column is one marked with `{}` in the logs. Forexample, given the above code, `jsonpayload` value should only show up in `jsonpayload` column, same for `tagid`, and `deploymentId` values. 
2. The columns should either not be truncated, or there should be clear documentation on the limit before truncation.

**What is the actual behavior?**

See internal Microsoft log as example: https://portal.microsoftgeneva.com/s/92AA0C01

1. The custom column values now show up both on the custom column, and the default body column
   - Our `jsonpayload` field includes actual json text. And back when I integrated OTel in spring/summer, the body column couldn't handle json (it either couldn't delimit " or { or } characters and so the entire entry was dropped). So the work around was to create just 1 column for the json payload, and that was handlable. So for that reason I know that the custom columns didn't use to show up on the default column. But now the json payload, and the other custom columns are showing up also in the body too!
2. Log columns are truncated after 16383 characters. So this seems to be the default, and ok, but the behaviour is not consistent! Does the limit apply to everything in the column? the whole row? or each string separately (where a string is `sb.ToString()`, and the custom columns in this example)? So now that the default column also includes the custom column values, the column itself has more than 16383 characters, but truncated when the large `jsonpayload` goes over 16383 characters.

## Additional Context

It seems like the behaviour of the OTel logging has changed. I also see some of the logs go to old IFx tables!

**Comment by xiang17** [comment]
Hi,

There has been changes since the version you used (1.1.1 was published in Oct 2021). Please try out newer versions and see if the issue persists: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md

Here is an internal doc you can refer to regarding logging https://eng.ms/docs/products/geneva/collect/instrument/opentelemetrydotnet/otel-logs-deep-dive
The latest version should not include the populated message in the body field.

Regarding column limit, there is indeed a limit currently on the string fields ([code link](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MessagePackSerializer.cs#L63)), because ETW has a limit of 64KB on total message size. However, it is worth a [revisit](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs#L446-L452) on how to truncate less and fit more data in the limited ETW space.

**Comment by alamoot** [comment]
Reading over the deep dive, I saw that the Geneva UI has setting option `Show formatted body column`. Unticking it, I no longer see the part c fields in the `body` column, like it was before. So assuming that option was later added and defaults to true, and hence why started seeing the part c fields in the body as well?

**Comment by alamoot** [comment]
For tracking purposes: Seeing the verification tool split long string to 16383 characters. Implemented truncation on long json payloads on our end. Have not updated to latest version of OTel.
