### ISSUE TITLE
Use RedisInstrumentation as standalone instrumentation?

### ISSUE THREAD

**Issue by nyitonandor** [open-telemetry/opentelemetry-dotnet-contrib#823]
# Question
Having the following OpenTelemetry configuration, I'm able to trace incoming requests and Redis related requests on the Console and through Application Insights.
```
serviceCollection.AddOpenTelemetry()
    .WithTracing(builder => builder
        .AddAspNetCoreInstrumentation()
        .AddRedisInstrumentation(this.multiplexer)
            .AddAzureMonitorTraceExporter(o => o.ConnectionString = "InstrumentationKey")
            .AddConsoleExporter())
    .StartWithHost();
```
My question would be if it's possible to rely on RedisInstrumentation without AspNetCoreInstrumentation. Currently if I remove `AddAspNetCoreInstrumentation()` nothing is being traced.

**OpenTelemetry NuGet packages**
OpenTelemetry 1.4.0-rc.1
OpenTelemetry.Exporter.Console 1.4.0-rc.1
OpenTelemetry.Extensions.Hosting 1.4.0-rc.1
OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.10
OpenTelemetry.Instrumentation.StackExchangeRedis 1.0.0-rc9.7
Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.3

**Runtime version** 
.NET 7.0

**Comment by alanwest** [comment]
Same as https://github.com/open-telemetry/opentelemetry-dotnet/issues/1217.

By default, the SDK uses the [parent-based sampler](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#parentbased). ASP.NET Core creates a parent activity which is not sampled since the instrumentation is not enabled. Therefore the Redis activity is not sampled because its parent was not sampled.

Workaround would be to use a different sampler like the AlwaysOn sampler.

```csharp
serviceCollection.AddOpenTelemetry()
    .WithTracing(builder => builder
        .SetSampler(new AlwaysOnSampler())
        .AddRedisInstrumentation(this.multiplexer)
            .AddAzureMonitorTraceExporter(o => o.ConnectionString = "InstrumentationKey")
            .AddConsoleExporter())
    .StartWithHost();
```

**Comment by nyitonandor** [comment]
Good stuff! 
It's working as expected. Thank you.
